
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.awt.image.BandedSampleModel ///

open class BandedSampleModel: ComponentSampleModel {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var BandedSampleModelJNIClass: jclass?

    /// protected int[] java.awt.image.ComponentSampleModel.bandOffsets

    private static var bandOffsets_FieldID: jfieldID?

    override open var bandOffsets: [Int32]! {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetObjectField( fieldName: "bandOffsets", fieldType: "[I", fieldCache: &BandedSampleModel.bandOffsets_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: [Int32](), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "bandOffsets", fieldType: "[I", fieldCache: &BandedSampleModel.bandOffsets_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected int[] java.awt.image.ComponentSampleModel.bankIndices

    private static var bankIndices_FieldID: jfieldID?

    override open var bankIndices: [Int32]! {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetObjectField( fieldName: "bankIndices", fieldType: "[I", fieldCache: &BandedSampleModel.bankIndices_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: [Int32](), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetObjectField( fieldName: "bankIndices", fieldType: "[I", fieldCache: &BandedSampleModel.bankIndices_FieldID, object: javaObject, value: __value.l, locals: &__locals )
        }
    }

    /// protected int java.awt.image.ComponentSampleModel.numBands

    private static var numBands_FieldID: jfieldID?

    override open var numBands: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "numBands", fieldType: "I", fieldCache: &BandedSampleModel.numBands_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetIntField( fieldName: "numBands", fieldType: "I", fieldCache: &BandedSampleModel.numBands_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected int java.awt.image.ComponentSampleModel.numBanks

    private static var numBanks_FieldID: jfieldID?

    override open var numBanks: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "numBanks", fieldType: "I", fieldCache: &BandedSampleModel.numBanks_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetIntField( fieldName: "numBanks", fieldType: "I", fieldCache: &BandedSampleModel.numBanks_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected int java.awt.image.ComponentSampleModel.scanlineStride

    private static var scanlineStride_FieldID: jfieldID?

    override open var scanlineStride: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "scanlineStride", fieldType: "I", fieldCache: &BandedSampleModel.scanlineStride_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetIntField( fieldName: "scanlineStride", fieldType: "I", fieldCache: &BandedSampleModel.scanlineStride_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected int java.awt.image.ComponentSampleModel.pixelStride

    private static var pixelStride_FieldID: jfieldID?

    override open var pixelStride: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "pixelStride", fieldType: "I", fieldCache: &BandedSampleModel.pixelStride_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetIntField( fieldName: "pixelStride", fieldType: "I", fieldCache: &BandedSampleModel.pixelStride_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected int java.awt.image.SampleModel.width

    private static var width_FieldID: jfieldID?

    override open var width: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "width", fieldType: "I", fieldCache: &BandedSampleModel.width_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetIntField( fieldName: "width", fieldType: "I", fieldCache: &BandedSampleModel.width_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected int java.awt.image.SampleModel.height

    private static var height_FieldID: jfieldID?

    override open var height: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "height", fieldType: "I", fieldCache: &BandedSampleModel.height_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetIntField( fieldName: "height", fieldType: "I", fieldCache: &BandedSampleModel.height_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// protected int java.awt.image.SampleModel.numBands

    /// protected int java.awt.image.SampleModel.dataType

    private static var dataType_FieldID: jfieldID?

    override open var dataType: Int {
        get {
            var __locals = [jobject]()
            let __value = JNIField.GetIntField( fieldName: "dataType", fieldType: "I", fieldCache: &BandedSampleModel.dataType_FieldID, object: javaObject, locals: &__locals )
            return JNIType.toSwift( type: Int(), from: __value )
        }
        set(newValue) {
            var __locals = [jobject]()
            let __value = JNIType.toJava( value: newValue, locals: &__locals )
            JNIField.SetIntField( fieldName: "dataType", fieldType: "I", fieldCache: &BandedSampleModel.dataType_FieldID, object: javaObject, value: __value.i, locals: &__locals )
        }
    }

    /// public java.awt.image.BandedSampleModel(int,int,int,int)

    private static var new_MethodID_1: jmethodID?

    public convenience init( dataType: Int, w: Int, h: Int, numBands: Int ) {
        var __args = [jvalue]( repeating: jvalue(), count: 4 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: dataType, locals: &__locals )
        __args[1] = JNIType.toJava( value: w, locals: &__locals )
        __args[2] = JNIType.toJava( value: h, locals: &__locals )
        __args[3] = JNIType.toJava( value: numBands, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/awt/image/BandedSampleModel", classCache: &BandedSampleModel.BandedSampleModelJNIClass, methodSig: "(IIII)V", methodCache: &BandedSampleModel.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _dataType: Int, _ _w: Int, _ _h: Int, _ _numBands: Int ) {
        self.init( dataType: _dataType, w: _w, h: _h, numBands: _numBands )
    }

    /// public java.awt.image.BandedSampleModel(int,int,int,int,int[],int[])

    private static var new_MethodID_2: jmethodID?

    public convenience init( dataType: Int, w: Int, h: Int, scanlineStride: Int, bankIndices: [Int32]?, bandOffsets: [Int32]? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 6 )
        var __locals = [jobject]()
        __args[0] = JNIType.toJava( value: dataType, locals: &__locals )
        __args[1] = JNIType.toJava( value: w, locals: &__locals )
        __args[2] = JNIType.toJava( value: h, locals: &__locals )
        __args[3] = JNIType.toJava( value: scanlineStride, locals: &__locals )
        __args[4] = JNIType.toJava( value: bankIndices, locals: &__locals )
        __args[5] = JNIType.toJava( value: bandOffsets, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/awt/image/BandedSampleModel", classCache: &BandedSampleModel.BandedSampleModelJNIClass, methodSig: "(IIII[I[I)V", methodCache: &BandedSampleModel.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _dataType: Int, _ _w: Int, _ _h: Int, _ _scanlineStride: Int, _ _bankIndices: [Int32]?, _ _bandOffsets: [Int32]? ) {
        self.init( dataType: _dataType, w: _w, h: _h, scanlineStride: _scanlineStride, bankIndices: _bankIndices, bandOffsets: _bandOffsets )
    }

    /// public int java.awt.image.BandedSampleModel.hashCode()

    /// public java.awt.image.DataBuffer java.awt.image.BandedSampleModel.createDataBuffer()

    /// public java.awt.image.SampleModel java.awt.image.BandedSampleModel.createSubsetSampleModel(int[])

    /// public void java.awt.image.BandedSampleModel.setDataElements(int,int,java.lang.Object,java.awt.image.DataBuffer)

    /// public void java.awt.image.BandedSampleModel.setPixel(int,int,int[],java.awt.image.DataBuffer)

    /// public void java.awt.image.BandedSampleModel.setPixels(int,int,int,int,int[],java.awt.image.DataBuffer)

    /// public void java.awt.image.BandedSampleModel.setSample(int,int,int,float,java.awt.image.DataBuffer)

    /// public void java.awt.image.BandedSampleModel.setSample(int,int,int,int,java.awt.image.DataBuffer)

    /// public void java.awt.image.BandedSampleModel.setSample(int,int,int,double,java.awt.image.DataBuffer)

    /// public void java.awt.image.BandedSampleModel.setSamples(int,int,int,int,int,int[],java.awt.image.DataBuffer)

    /// public java.lang.Object java.awt.image.BandedSampleModel.getDataElements(int,int,java.lang.Object,java.awt.image.DataBuffer)

    /// public java.awt.image.SampleModel java.awt.image.BandedSampleModel.createCompatibleSampleModel(int,int)

    /// public int[] java.awt.image.BandedSampleModel.getPixel(int,int,int[],java.awt.image.DataBuffer)

    /// public int[] java.awt.image.BandedSampleModel.getPixels(int,int,int,int,int[],java.awt.image.DataBuffer)

    /// public int java.awt.image.BandedSampleModel.getSample(int,int,int,java.awt.image.DataBuffer)

    /// public float java.awt.image.BandedSampleModel.getSampleFloat(int,int,int,java.awt.image.DataBuffer)

    /// public double java.awt.image.BandedSampleModel.getSampleDouble(int,int,int,java.awt.image.DataBuffer)

    /// public int[] java.awt.image.BandedSampleModel.getSamples(int,int,int,int,int,int[],java.awt.image.DataBuffer)

    /// private static int[] java.awt.image.BandedSampleModel.createOffsetArray(int)

    /// private static int[] java.awt.image.BandedSampleModel.createIndicesArray(int)

}

