
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// interface java.awt.peer.LightweightPeer ///

public protocol LightweightPeer: ComponentPeer {

}


open class LightweightPeerForward: ComponentPeerForward, LightweightPeer {

    private static var LightweightPeerJNIClass: jclass?

}


