
import java_swift

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// class java.awt.PageAttributes$ColorType ///

open class PageAttributes_ColorType: /* java.awt.AttributeValue */ UnclassedObject {

    public convenience init?( casting object: java_swift.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var PageAttributes_ColorTypeJNIClass: jclass?

    /// private static final int java.awt.PageAttributes$ColorType.I_COLOR

    /// private static final int java.awt.PageAttributes$ColorType.I_MONOCHROME

    /// private static final java.lang.String[] java.awt.PageAttributes$ColorType.NAMES

    /// public static final java.awt.PageAttributes$ColorType java.awt.PageAttributes$ColorType.COLOR

    private static var COLOR_FieldID: jfieldID?

    open static var COLOR: PageAttributes_ColorType! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "COLOR", fieldType: "Ljava/awt/PageAttributes$ColorType;", fieldCache: &COLOR_FieldID, className: "java/awt/PageAttributes$ColorType", classCache: &PageAttributes_ColorTypeJNIClass )
            return __value != nil ? PageAttributes_ColorType( javaObject: __value ) : nil
        }
    }

    /// public static final java.awt.PageAttributes$ColorType java.awt.PageAttributes$ColorType.MONOCHROME

    private static var MONOCHROME_FieldID: jfieldID?

    open static var MONOCHROME: PageAttributes_ColorType! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "MONOCHROME", fieldType: "Ljava/awt/PageAttributes$ColorType;", fieldCache: &MONOCHROME_FieldID, className: "java/awt/PageAttributes$ColorType", classCache: &PageAttributes_ColorTypeJNIClass )
            return __value != nil ? PageAttributes_ColorType( javaObject: __value ) : nil
        }
    }

    /// private static final sun.util.logging.PlatformLogger java.awt.AttributeValue.log

    /// private final int java.awt.AttributeValue.value

    /// private final java.lang.String[] java.awt.AttributeValue.names

    /// private java.awt.PageAttributes$ColorType(int)

    /// public java.lang.String java.awt.PageAttributes$ColorType.toString()

    /// public int java.awt.PageAttributes$ColorType.hashCode()

}

