
import java_swift
import java_lang

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:35:57 GMT 2016 ///

/// class java.awt.geom.Path2D$Float ///

open class Path2D_Float: Path2D, /* java.io.Serializable */ UnclassedProtocol {

    public convenience init?( casting object: java_lang.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "java.awt.geom.Path2D$Float", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var Path2D_FloatJNIClass: jclass?

    /// transient float[] java.awt.geom.Path2D$Float.floatCoords

    /// private static final long java.awt.geom.Path2D$Float.serialVersionUID

    /// public static final int java.awt.geom.Path2D.WIND_EVEN_ODD

    /// public static final int java.awt.geom.Path2D.WIND_NON_ZERO

    /// private static final byte java.awt.geom.Path2D.SEG_MOVETO

    /// private static final byte java.awt.geom.Path2D.SEG_LINETO

    /// private static final byte java.awt.geom.Path2D.SEG_QUADTO

    /// private static final byte java.awt.geom.Path2D.SEG_CUBICTO

    /// private static final byte java.awt.geom.Path2D.SEG_CLOSE

    /// transient byte[] java.awt.geom.Path2D.pointTypes

    /// transient int java.awt.geom.Path2D.numTypes

    /// transient int java.awt.geom.Path2D.numCoords

    /// transient int java.awt.geom.Path2D.windingRule

    /// static final int java.awt.geom.Path2D.INIT_SIZE

    /// static final int java.awt.geom.Path2D.EXPAND_MAX

    /// private static final byte java.awt.geom.Path2D.SERIAL_STORAGE_FLT_ARRAY

    /// private static final byte java.awt.geom.Path2D.SERIAL_STORAGE_DBL_ARRAY

    /// private static final byte java.awt.geom.Path2D.SERIAL_SEG_FLT_MOVETO

    /// private static final byte java.awt.geom.Path2D.SERIAL_SEG_FLT_LINETO

    /// private static final byte java.awt.geom.Path2D.SERIAL_SEG_FLT_QUADTO

    /// private static final byte java.awt.geom.Path2D.SERIAL_SEG_FLT_CUBICTO

    /// private static final byte java.awt.geom.Path2D.SERIAL_SEG_DBL_MOVETO

    /// private static final byte java.awt.geom.Path2D.SERIAL_SEG_DBL_LINETO

    /// private static final byte java.awt.geom.Path2D.SERIAL_SEG_DBL_QUADTO

    /// private static final byte java.awt.geom.Path2D.SERIAL_SEG_DBL_CUBICTO

    /// private static final byte java.awt.geom.Path2D.SERIAL_SEG_CLOSE

    /// private static final byte java.awt.geom.Path2D.SERIAL_PATH_END

    /// public java.awt.geom.Path2D$Float()

    private static var new_MethodID_1: jmethodID?

    public convenience init() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __object = JNIMethod.NewObject( className: "java/awt/geom/Path2D$Float", classCache: &Path2D_Float.Path2D_FloatJNIClass, methodSig: "()V", methodCache: &Path2D_Float.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    /// public java.awt.geom.Path2D$Float(int)

    private static var new_MethodID_2: jmethodID?

    public convenience init( arg0: Int ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/awt/geom/Path2D$Float", classCache: &Path2D_Float.Path2D_FloatJNIClass, methodSig: "(I)V", methodCache: &Path2D_Float.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Int ) {
        self.init( arg0: _arg0 )
    }

    /// public java.awt.geom.Path2D$Float(int,int)

    private static var new_MethodID_3: jmethodID?

    public convenience init( arg0: Int, arg1: Int ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/awt/geom/Path2D$Float", classCache: &Path2D_Float.Path2D_FloatJNIClass, methodSig: "(II)V", methodCache: &Path2D_Float.new_MethodID_3, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Int, _ _arg1: Int ) {
        self.init( arg0: _arg0, arg1: _arg1 )
    }

    /// public java.awt.geom.Path2D$Float(java.awt.Shape)

    private static var new_MethodID_4: jmethodID?

    public convenience init( arg0: Shape? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        let __object = JNIMethod.NewObject( className: "java/awt/geom/Path2D$Float", classCache: &Path2D_Float.Path2D_FloatJNIClass, methodSig: "(Ljava/awt/Shape;)V", methodCache: &Path2D_Float.new_MethodID_4, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Shape? ) {
        self.init( arg0: _arg0 )
    }

    /// public java.awt.geom.Path2D$Float(java.awt.Shape,java.awt.geom.AffineTransform)

    private static var new_MethodID_5: jmethodID?

    public convenience init( arg0: Shape?, arg1: AffineTransform? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/awt/geom/Path2D$Float", classCache: &Path2D_Float.Path2D_FloatJNIClass, methodSig: "(Ljava/awt/Shape;Ljava/awt/geom/AffineTransform;)V", methodCache: &Path2D_Float.new_MethodID_5, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Shape?, _ _arg1: AffineTransform? ) {
        self.init( arg0: _arg0, arg1: _arg1 )
    }

    /// public final void java.awt.geom.Path2D$Float.append(java.awt.geom.PathIterator,boolean)

    /// void java.awt.geom.Path2D$Float.append(float,float)

    /// void java.awt.geom.Path2D$Float.append(double,double)

    /// public final java.lang.Object java.awt.geom.Path2D$Float.clone()

    /// public final void java.awt.geom.Path2D$Float.transform(java.awt.geom.AffineTransform)

    /// private void java.awt.geom.Path2D$Float.writeObject(java.io.ObjectOutputStream) throws java.io.IOException

    /// private void java.awt.geom.Path2D$Float.readObject(java.io.ObjectInputStream) throws java.lang.ClassNotFoundException,java.io.IOException

    /// public final synchronized void java.awt.geom.Path2D$Float.moveTo(double,double)

    /// public final synchronized void java.awt.geom.Path2D$Float.moveTo(float,float)

    private static var moveTo_MethodID_6: jmethodID?

    open func moveTo( arg0: Float, arg1: Float ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "moveTo", methodSig: "(FF)V", methodCache: &Path2D_Float.moveTo_MethodID_6, args: &__args, locals: &__locals )
    }

    open func moveTo( _ _arg0: Float, _ _arg1: Float ) {
        moveTo( arg0: _arg0, arg1: _arg1 )
    }

    /// public final synchronized void java.awt.geom.Path2D$Float.lineTo(float,float)

    private static var lineTo_MethodID_7: jmethodID?

    open func lineTo( arg0: Float, arg1: Float ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "lineTo", methodSig: "(FF)V", methodCache: &Path2D_Float.lineTo_MethodID_7, args: &__args, locals: &__locals )
    }

    open func lineTo( _ _arg0: Float, _ _arg1: Float ) {
        lineTo( arg0: _arg0, arg1: _arg1 )
    }

    /// public final synchronized void java.awt.geom.Path2D$Float.lineTo(double,double)

    /// public final synchronized void java.awt.geom.Path2D$Float.quadTo(double,double,double,double)

    /// public final synchronized void java.awt.geom.Path2D$Float.quadTo(float,float,float,float)

    private static var quadTo_MethodID_8: jmethodID?

    open func quadTo( arg0: Float, arg1: Float, arg2: Float, arg3: Float ) {
        var __args = [jvalue]( repeating: jvalue(), count: 4 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        __args[2] = JNIType.encode( value: arg2, locals: &__locals )
        __args[3] = JNIType.encode( value: arg3, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "quadTo", methodSig: "(FFFF)V", methodCache: &Path2D_Float.quadTo_MethodID_8, args: &__args, locals: &__locals )
    }

    open func quadTo( _ _arg0: Float, _ _arg1: Float, _ _arg2: Float, _ _arg3: Float ) {
        quadTo( arg0: _arg0, arg1: _arg1, arg2: _arg2, arg3: _arg3 )
    }

    /// public final synchronized void java.awt.geom.Path2D$Float.curveTo(double,double,double,double,double,double)

    /// public final synchronized void java.awt.geom.Path2D$Float.curveTo(float,float,float,float,float,float)

    private static var curveTo_MethodID_9: jmethodID?

    open func curveTo( arg0: Float, arg1: Float, arg2: Float, arg3: Float, arg4: Float, arg5: Float ) {
        var __args = [jvalue]( repeating: jvalue(), count: 6 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        __args[2] = JNIType.encode( value: arg2, locals: &__locals )
        __args[3] = JNIType.encode( value: arg3, locals: &__locals )
        __args[4] = JNIType.encode( value: arg4, locals: &__locals )
        __args[5] = JNIType.encode( value: arg5, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "curveTo", methodSig: "(FFFFFF)V", methodCache: &Path2D_Float.curveTo_MethodID_9, args: &__args, locals: &__locals )
    }

    open func curveTo( _ _arg0: Float, _ _arg1: Float, _ _arg2: Float, _ _arg3: Float, _ _arg4: Float, _ _arg5: Float ) {
        curveTo( arg0: _arg0, arg1: _arg1, arg2: _arg2, arg3: _arg3, arg4: _arg4, arg5: _arg5 )
    }

    /// public java.awt.geom.PathIterator java.awt.geom.Path2D$Float.getPathIterator(java.awt.geom.AffineTransform)

    /// public final synchronized java.awt.geom.Rectangle2D java.awt.geom.Path2D$Float.getBounds2D()

    /// java.awt.geom.Point2D java.awt.geom.Path2D$Float.getPoint(int)

    /// float[] java.awt.geom.Path2D$Float.cloneCoordsFloat(java.awt.geom.AffineTransform)

    /// double[] java.awt.geom.Path2D$Float.cloneCoordsDouble(java.awt.geom.AffineTransform)

    /// void java.awt.geom.Path2D$Float.needRoom(boolean,int)

    /// int java.awt.geom.Path2D$Float.pointCrossings(double,double)

    /// int java.awt.geom.Path2D$Float.rectCrossings(double,double,double,double)

}
