
import java_swift
import java_lang

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:35:00 GMT 2016 ///

/// class java.awt.TrayIcon$MessageType ///

open class TrayIcon_MessageType: java_lang.Enum {

    public convenience init?( casting object: java_lang.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "java.awt.TrayIcon$MessageType", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var TrayIcon_MessageTypeJNIClass: jclass?

    /// public static final java.awt.TrayIcon$MessageType java.awt.TrayIcon$MessageType.ERROR

    private static var ERROR_FieldID: jfieldID?

    open static var ERROR: TrayIcon_MessageType! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "ERROR", fieldType: "Ljava/awt/TrayIcon$MessageType;", fieldCache: &ERROR_FieldID, className: "java/awt/TrayIcon$MessageType", classCache: &TrayIcon_MessageTypeJNIClass )
            return __value != nil ? TrayIcon_MessageType( javaObject: __value ) : nil
        }
    }

    /// public static final java.awt.TrayIcon$MessageType java.awt.TrayIcon$MessageType.WARNING

    private static var WARNING_FieldID: jfieldID?

    open static var WARNING: TrayIcon_MessageType! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "WARNING", fieldType: "Ljava/awt/TrayIcon$MessageType;", fieldCache: &WARNING_FieldID, className: "java/awt/TrayIcon$MessageType", classCache: &TrayIcon_MessageTypeJNIClass )
            return __value != nil ? TrayIcon_MessageType( javaObject: __value ) : nil
        }
    }

    /// public static final java.awt.TrayIcon$MessageType java.awt.TrayIcon$MessageType.INFO

    private static var INFO_FieldID: jfieldID?

    open static var INFO: TrayIcon_MessageType! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "INFO", fieldType: "Ljava/awt/TrayIcon$MessageType;", fieldCache: &INFO_FieldID, className: "java/awt/TrayIcon$MessageType", classCache: &TrayIcon_MessageTypeJNIClass )
            return __value != nil ? TrayIcon_MessageType( javaObject: __value ) : nil
        }
    }

    /// public static final java.awt.TrayIcon$MessageType java.awt.TrayIcon$MessageType.NONE

    private static var NONE_FieldID: jfieldID?

    open static var NONE: TrayIcon_MessageType! {
        get {
            let __value = JNIField.GetStaticObjectField( fieldName: "NONE", fieldType: "Ljava/awt/TrayIcon$MessageType;", fieldCache: &NONE_FieldID, className: "java/awt/TrayIcon$MessageType", classCache: &TrayIcon_MessageTypeJNIClass )
            return __value != nil ? TrayIcon_MessageType( javaObject: __value ) : nil
        }
    }

    /// private static final java.awt.TrayIcon$MessageType[] java.awt.TrayIcon$MessageType.$VALUES

    /// private final java.lang.String java.lang.Enum.name

    /// private final int java.lang.Enum.ordinal

    /// private java.awt.TrayIcon$MessageType(java.lang.String,int)

    /// public static java.awt.TrayIcon$MessageType[] java.awt.TrayIcon$MessageType.values()

    private static var values_MethodID_1: jmethodID?

    open class func values() -> [TrayIcon_MessageType]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/awt/TrayIcon$MessageType", classCache: &TrayIcon_MessageTypeJNIClass, methodName: "values", methodSig: "()[Ljava/awt/TrayIcon$MessageType;", methodCache: &values_MethodID_1, args: &__args, locals: &__locals )
        return JNIType.decode( type: [TrayIcon_MessageType](), from: __return )
    }


    /// public static java.awt.TrayIcon$MessageType java.awt.TrayIcon$MessageType.valueOf(java.lang.String)

    private static var valueOf_MethodID_2: jmethodID?

    open class func valueOf( arg0: String? ) -> TrayIcon_MessageType! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/awt/TrayIcon$MessageType", classCache: &TrayIcon_MessageTypeJNIClass, methodName: "valueOf", methodSig: "(Ljava/lang/String;)Ljava/awt/TrayIcon$MessageType;", methodCache: &valueOf_MethodID_2, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? TrayIcon_MessageType( javaObject: __return ) : nil
    }

    open class func valueOf( _ _arg0: String? ) -> TrayIcon_MessageType! {
        return valueOf( arg0: _arg0 )
    }

}
