
import java_swift
import java_lang
import java_util

/// generated by: genswift.java 'java/lang|java/util|java/sql|java/awt|javax/swing' ///

/// JAVA_HOME: /Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home ///
/// Tue Dec 20 11:36:02 GMT 2016 ///

/// class java.awt.Window ///

open class Window: Container {

    public convenience init?( casting object: java_lang.JavaObject, _ file: StaticString = #file, _ line: Int = #line ) {
        self.init( javaObject: nil )
        if !object.validDownCast( toJavaClass: "java.awt.Window", file, line ) {
            return nil
        }
        object.withJavaObject {
            self.javaObject = $0
        }
    }

    private static var WindowJNIClass: jclass?

    /// java.lang.String java.awt.Window.warningString

    /// transient java.util.List java.awt.Window.icons

    /// private transient java.awt.Component java.awt.Window.temporaryLostComponent

    /// static boolean java.awt.Window.systemSyncLWRequests

    /// boolean java.awt.Window.syncLWRequests

    /// transient boolean java.awt.Window.beforeFirstShow

    /// private transient boolean java.awt.Window.disposing

    /// static final int java.awt.Window.OPENED

    /// int java.awt.Window.state

    /// private boolean java.awt.Window.alwaysOnTop

    /// private static final sun.awt.util.IdentityArrayList java.awt.Window.allWindows

    /// transient java.util.Vector java.awt.Window.ownedWindowList

    /// private transient java.lang.ref.WeakReference java.awt.Window.weakThis

    /// transient boolean java.awt.Window.showWithParent

    /// transient java.awt.Dialog java.awt.Window.modalBlocker

    /// java.awt.Dialog$ModalExclusionType java.awt.Window.modalExclusionType

    /// transient java.awt.event.WindowListener java.awt.Window.windowListener

    /// transient java.awt.event.WindowStateListener java.awt.Window.windowStateListener

    /// transient java.awt.event.WindowFocusListener java.awt.Window.windowFocusListener

    /// transient java.awt.im.InputContext java.awt.Window.inputContext

    /// private transient java.lang.Object java.awt.Window.inputContextLock

    /// private java.awt.FocusManager java.awt.Window.focusMgr

    /// private boolean java.awt.Window.focusableWindowState

    /// transient boolean java.awt.Window.isInShow

    /// private static final java.lang.String java.awt.Window.base

    /// private static int java.awt.Window.nameCounter

    /// private static final long java.awt.Window.serialVersionUID

    /// private static final java.util.logging.Logger java.awt.Window.log

    /// private static final boolean java.awt.Window.locationByPlatformProp

    /// transient boolean java.awt.Window.isTrayIconWindow

    /// private transient volatile int java.awt.Window.securityWarningWidth

    /// private transient volatile int java.awt.Window.securityWarningHeight

    /// private transient double java.awt.Window.securityWarningPointX

    /// private transient double java.awt.Window.securityWarningPointY

    /// private transient float java.awt.Window.securityWarningAlignmentX

    /// private transient float java.awt.Window.securityWarningAlignmentY

    /// transient java.lang.Object java.awt.Window.anchor

    /// private static final java.util.concurrent.atomic.AtomicBoolean java.awt.Window.beforeFirstWindowShown

    /// private int java.awt.Window.windowSerializedDataVersion

    /// private boolean java.awt.Window.locationByPlatform

    /// private static final java.awt.Color java.awt.Window.TRANSPARENT_BACKGROUND_COLOR

    /// private transient float java.awt.Window.opacity

    /// private transient java.awt.Shape java.awt.Window.shape

    /// private transient boolean java.awt.Window.opaque

    /// private static final java.awt.Component[] java.awt.Container.EMPTY_ARRAY

    /// private java.util.List java.awt.Container.component

    /// java.awt.LayoutManager java.awt.Container.layoutMgr

    /// private java.awt.LightweightDispatcher java.awt.Container.dispatcher

    /// private transient java.awt.FocusTraversalPolicy java.awt.Container.focusTraversalPolicy

    /// private boolean java.awt.Container.focusCycleRoot

    /// private boolean java.awt.Container.focusTraversalPolicyProvider

    /// private transient java.util.Set java.awt.Container.printingThreads

    /// private transient boolean java.awt.Container.printing

    /// transient java.awt.event.ContainerListener java.awt.Container.containerListener

    /// transient int java.awt.Container.listeningChildren

    /// transient int java.awt.Container.listeningBoundsChildren

    /// transient int java.awt.Container.descendantsCount

    /// transient java.awt.Color java.awt.Container.preserveBackgroundColor

    /// private static final long java.awt.Container.serialVersionUID

    /// private static final sun.awt.DebugHelper java.awt.Container.dbg

    /// static final boolean java.awt.Container.INCLUDE_SELF

    /// static final boolean java.awt.Container.SEARCH_HEAVYWEIGHTS

    /// private transient int java.awt.Container.numOfHWComponents

    /// private transient int java.awt.Container.numOfLWComponents

    /// private static final java.util.logging.Logger java.awt.Container.mixingLog

    /// private static final java.io.ObjectStreamField[] java.awt.Container.serialPersistentFields

    /// transient java.awt.Component java.awt.Container.modalComp

    /// transient sun.awt.AppContext java.awt.Container.modalAppContext

    /// private int java.awt.Container.containerSerializedDataVersion

    /// static final boolean java.awt.Container.$assertionsDisabled

    /// private static final java.util.logging.Logger java.awt.Component.focusLog

    /// private static final java.util.logging.Logger java.awt.Component.log

    /// private static final java.util.logging.Logger java.awt.Component.mixingLog

    /// transient java.awt.peer.ComponentPeer java.awt.Component.peer

    /// transient java.awt.Container java.awt.Component.parent

    /// transient sun.awt.AppContext java.awt.Component.appContext

    /// int java.awt.Component.x

    /// int java.awt.Component.y

    /// int java.awt.Component.width

    /// int java.awt.Component.height

    /// java.awt.Color java.awt.Component.foreground

    /// java.awt.Color java.awt.Component.background

    /// java.awt.Font java.awt.Component.font

    /// java.awt.Font java.awt.Component.peerFont

    /// java.awt.Cursor java.awt.Component.cursor

    /// java.util.Locale java.awt.Component.locale

    /// transient java.awt.GraphicsConfiguration java.awt.Component.graphicsConfig

    /// transient java.awt.image.BufferStrategy java.awt.Component.bufferStrategy

    /// boolean java.awt.Component.ignoreRepaint

    /// boolean java.awt.Component.visible

    /// boolean java.awt.Component.enabled

    /// private volatile boolean java.awt.Component.valid

    /// java.awt.dnd.DropTarget java.awt.Component.dropTarget

    /// java.util.Vector java.awt.Component.popups

    /// private java.lang.String java.awt.Component.name

    /// private boolean java.awt.Component.nameExplicitlySet

    /// private boolean java.awt.Component.focusable

    /// private static final int java.awt.Component.FOCUS_TRAVERSABLE_UNKNOWN

    /// private static final int java.awt.Component.FOCUS_TRAVERSABLE_DEFAULT

    /// private static final int java.awt.Component.FOCUS_TRAVERSABLE_SET

    /// private int java.awt.Component.isFocusTraversableOverridden

    /// java.util.Set[] java.awt.Component.focusTraversalKeys

    /// private static final java.lang.String[] java.awt.Component.focusTraversalKeyPropertyNames

    /// private boolean java.awt.Component.focusTraversalKeysEnabled

    /// static final java.lang.Object java.awt.Component.LOCK

    /// private transient volatile java.security.AccessControlContext java.awt.Component.acc

    /// java.awt.Dimension java.awt.Component.minSize

    /// boolean java.awt.Component.minSizeSet

    /// java.awt.Dimension java.awt.Component.prefSize

    /// boolean java.awt.Component.prefSizeSet

    /// java.awt.Dimension java.awt.Component.maxSize

    /// boolean java.awt.Component.maxSizeSet

    /// transient java.awt.ComponentOrientation java.awt.Component.componentOrientation

    /// boolean java.awt.Component.newEventsOnly

    /// transient java.awt.event.ComponentListener java.awt.Component.componentListener

    /// transient java.awt.event.FocusListener java.awt.Component.focusListener

    /// transient java.awt.event.HierarchyListener java.awt.Component.hierarchyListener

    /// transient java.awt.event.HierarchyBoundsListener java.awt.Component.hierarchyBoundsListener

    /// transient java.awt.event.KeyListener java.awt.Component.keyListener

    /// transient java.awt.event.MouseListener java.awt.Component.mouseListener

    /// transient java.awt.event.MouseMotionListener java.awt.Component.mouseMotionListener

    /// transient java.awt.event.MouseWheelListener java.awt.Component.mouseWheelListener

    /// transient java.awt.event.InputMethodListener java.awt.Component.inputMethodListener

    /// transient java.lang.RuntimeException java.awt.Component.windowClosingException

    /// static final java.lang.String java.awt.Component.actionListenerK

    /// static final java.lang.String java.awt.Component.adjustmentListenerK

    /// static final java.lang.String java.awt.Component.componentListenerK

    /// static final java.lang.String java.awt.Component.containerListenerK

    /// static final java.lang.String java.awt.Component.focusListenerK

    /// static final java.lang.String java.awt.Component.itemListenerK

    /// static final java.lang.String java.awt.Component.keyListenerK

    /// static final java.lang.String java.awt.Component.mouseListenerK

    /// static final java.lang.String java.awt.Component.mouseMotionListenerK

    /// static final java.lang.String java.awt.Component.mouseWheelListenerK

    /// static final java.lang.String java.awt.Component.textListenerK

    /// static final java.lang.String java.awt.Component.ownedWindowK

    /// static final java.lang.String java.awt.Component.windowListenerK

    /// static final java.lang.String java.awt.Component.inputMethodListenerK

    /// static final java.lang.String java.awt.Component.hierarchyListenerK

    /// static final java.lang.String java.awt.Component.hierarchyBoundsListenerK

    /// static final java.lang.String java.awt.Component.windowStateListenerK

    /// static final java.lang.String java.awt.Component.windowFocusListenerK

    /// long java.awt.Component.eventMask

    /// private static final sun.awt.DebugHelper java.awt.Component.dbg

    /// static boolean java.awt.Component.isInc

    /// static int java.awt.Component.incRate

    /// public static final float java.awt.Component.TOP_ALIGNMENT

    /// public static final float java.awt.Component.CENTER_ALIGNMENT

    /// public static final float java.awt.Component.BOTTOM_ALIGNMENT

    /// public static final float java.awt.Component.LEFT_ALIGNMENT

    /// public static final float java.awt.Component.RIGHT_ALIGNMENT

    /// private static final long java.awt.Component.serialVersionUID

    /// private java.beans.PropertyChangeSupport java.awt.Component.changeSupport

    /// private transient java.lang.Object java.awt.Component.objectLock

    /// boolean java.awt.Component.isPacked

    /// private transient java.lang.Object java.awt.Component.privateKey

    /// private int java.awt.Component.boundsOp

    /// private transient sun.java2d.pipe.Region java.awt.Component.compoundShape

    /// private transient sun.java2d.pipe.Region java.awt.Component.mixingCutoutRegion

    /// private transient boolean java.awt.Component.isAddNotifyComplete

    /// transient boolean java.awt.Component.backgroundEraseDisabled

    /// transient java.awt.EventQueueItem[] java.awt.Component.eventCache

    /// private transient boolean java.awt.Component.coalescingEnabled

    /// private static final java.util.Map java.awt.Component.coalesceMap

    /// private static final java.lang.Class[] java.awt.Component.coalesceEventsParams

    /// private static sun.awt.RequestFocusController java.awt.Component.requestFocusController

    /// private int java.awt.Component.componentSerializedDataVersion

    /// transient java.awt.Component$NativeInLightFixer java.awt.Component.nativeInLightFixer

    /// javax.accessibility.AccessibleContext java.awt.Component.accessibleContext

    /// static final boolean java.awt.Component.$assertionsDisabled

    /// public static final int java.awt.image.ImageObserver.WIDTH

    /// public static final int java.awt.image.ImageObserver.HEIGHT

    /// public static final int java.awt.image.ImageObserver.PROPERTIES

    /// public static final int java.awt.image.ImageObserver.SOMEBITS

    /// public static final int java.awt.image.ImageObserver.FRAMEBITS

    /// public static final int java.awt.image.ImageObserver.ALLBITS

    /// public static final int java.awt.image.ImageObserver.ERROR

    /// public static final int java.awt.image.ImageObserver.ABORT

    /// public java.awt.Window(java.awt.Window,java.awt.GraphicsConfiguration)

    private static var new_MethodID_1: jmethodID?

    public convenience init( arg0: Window?, arg1: GraphicsConfiguration? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/awt/Window", classCache: &Window.WindowJNIClass, methodSig: "(Ljava/awt/Window;Ljava/awt/GraphicsConfiguration;)V", methodCache: &Window.new_MethodID_1, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Window?, _ _arg1: GraphicsConfiguration? ) {
        self.init( arg0: _arg0, arg1: _arg1 )
    }

    /// java.awt.Window(java.awt.GraphicsConfiguration)

    /// java.awt.Window() throws java.awt.HeadlessException

    /// public java.awt.Window(java.awt.Frame)

    /// public java.awt.Window(java.awt.Window)

    private static var new_MethodID_2: jmethodID?

    public convenience init( arg0: Window? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        let __object = JNIMethod.NewObject( className: "java/awt/Window", classCache: &Window.WindowJNIClass, methodSig: "(Ljava/awt/Window;)V", methodCache: &Window.new_MethodID_2, args: &__args, locals: &__locals )
        self.init( javaObject: __object )
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Window? ) {
        self.init( arg0: _arg0 )
    }

    /// private static double java.awt.Window.limit(double,double,double)

    /// static void java.awt.Window.access$100(sun.awt.AppContext,java.lang.ref.WeakReference)

    /// static boolean java.awt.Window.access$202(java.awt.Window,boolean)

    /// static java.lang.ref.WeakReference java.awt.Window.access$000(java.awt.Window)

    /// private void java.awt.Window.init(java.awt.GraphicsConfiguration)

    /// private void java.awt.Window.writeObject(java.io.ObjectOutputStream) throws java.io.IOException

    /// static java.lang.Object java.awt.Window.access$300(java.awt.Window)

    /// static float java.awt.Window.access$400(java.awt.Window)

    /// private void java.awt.Window.readObject(java.io.ObjectInputStream) throws java.lang.ClassNotFoundException,java.io.IOException,java.awt.HeadlessException

    /// static void java.awt.Window.access$500(java.awt.Window)

    /// static java.awt.Shape java.awt.Window.access$600(java.awt.Window)

    /// static void java.awt.Window.access$700(java.awt.Window)

    /// static boolean java.awt.Window.access$800(java.awt.Window)

    /// public void java.awt.Window.setSize(int,int)

    /// public void java.awt.Window.setSize(java.awt.Dimension)

    /// private static void java.awt.Window.initIDs()

    /// static void java.awt.Window.access$1000(java.awt.Window)

    /// static java.awt.Shape java.awt.Window.access$602(java.awt.Window,java.awt.Shape)

    /// static void java.awt.Window.access$900(java.awt.Window)

    /// static int java.awt.Window.access$1102(java.awt.Window,int)

    /// static int java.awt.Window.access$1200(java.awt.Window)

    /// static double java.awt.Window.access$1302(java.awt.Window,double)

    /// static float java.awt.Window.access$1602(java.awt.Window,float)

    /// static java.awt.geom.Point2D java.awt.Window.access$1700(java.awt.Window,double,double,double,double)

    /// public java.awt.Window java.awt.Window.getOwner()

    private static var getOwner_MethodID_3: jmethodID?

    open func getOwner() -> Window! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getOwner", methodSig: "()Ljava/awt/Window;", methodCache: &Window.getOwner_MethodID_3, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Window( javaObject: __return ) : nil
    }


    /// static int java.awt.Window.access$1100(java.awt.Window)

    /// static float java.awt.Window.access$402(java.awt.Window,float)

    /// public java.util.Locale java.awt.Window.getLocale()

    /// public boolean java.awt.Window.postEvent(java.awt.Event)

    /// boolean java.awt.Window.isModalExcluded(java.awt.Dialog$ModalExclusionType)

    /// public void java.awt.Window.dispose()

    private static var dispose_MethodID_4: jmethodID?

    open func dispose() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "dispose", methodSig: "()V", methodCache: &Window.dispose_MethodID_4, args: &__args, locals: &__locals )
    }


    /// public void java.awt.Window.setModalExclusionType(java.awt.Dialog$ModalExclusionType)

    private static var setModalExclusionType_MethodID_5: jmethodID?

    open func setModalExclusionType( arg0: Dialog_ModalExclusionType? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setModalExclusionType", methodSig: "(Ljava/awt/Dialog$ModalExclusionType;)V", methodCache: &Window.setModalExclusionType_MethodID_5, args: &__args, locals: &__locals )
    }

    open func setModalExclusionType( _ _arg0: Dialog_ModalExclusionType? ) {
        setModalExclusionType( arg0: _arg0 )
    }

    /// public java.awt.Dialog$ModalExclusionType java.awt.Window.getModalExclusionType()

    private static var getModalExclusionType_MethodID_6: jmethodID?

    open func getModalExclusionType() -> Dialog_ModalExclusionType! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getModalExclusionType", methodSig: "()Ljava/awt/Dialog$ModalExclusionType;", methodCache: &Window.getModalExclusionType_MethodID_6, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Dialog_ModalExclusionType( javaObject: __return ) : nil
    }


    /// public void java.awt.Window.addPropertyChangeListener(java.beans.PropertyChangeListener)

    /// public void java.awt.Window.addPropertyChangeListener(java.lang.String,java.beans.PropertyChangeListener)

    /// public boolean java.awt.Window.isAlwaysOnTopSupported()

    private static var isAlwaysOnTopSupported_MethodID_7: jmethodID?

    open func isAlwaysOnTopSupported() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isAlwaysOnTopSupported", methodSig: "()Z", methodCache: &Window.isAlwaysOnTopSupported_MethodID_7, args: &__args, locals: &__locals )
        return JNIType.decode( type: Bool(), from: __return )
    }


    /// public java.util.EventListener[] java.awt.Window.getListeners(java.lang.Class)

    /// void java.awt.Window.dispatchEventImpl(java.awt.AWTEvent)

    /// public void java.awt.Window.setVisible(boolean)

    /// public void java.awt.Window.toFront()

    private static var toFront_MethodID_8: jmethodID?

    open func toFront() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "toFront", methodSig: "()V", methodCache: &Window.toFront_MethodID_8, args: &__args, locals: &__locals )
    }


    /// public void java.awt.Window.addNotify()

    /// public javax.accessibility.AccessibleContext java.awt.Window.getAccessibleContext()

    /// public boolean java.awt.Window.isShowing()

    /// public void java.awt.Window.paint(java.awt.Graphics)

    /// public void java.awt.Window.setMinimumSize(java.awt.Dimension)

    /// public void java.awt.Window.reshape(int,int,int,int)

    /// public void java.awt.Window.removeNotify()

    /// public final boolean java.awt.Window.isFocusCycleRoot()

    /// public final java.awt.Container java.awt.Window.getFocusCycleRootAncestor()

    /// public void java.awt.Window.setBounds(java.awt.Rectangle)

    /// public void java.awt.Window.setBounds(int,int,int,int)

    /// boolean java.awt.Window.canContainFocusOwner(java.awt.Component)

    /// void java.awt.Window.adjustDecendantsOnParent(int)

    /// boolean java.awt.Window.eventEnabled(java.awt.AWTEvent)

    /// protected void java.awt.Window.processEvent(java.awt.AWTEvent)

    private static var processEvent_MethodID_9: jmethodID?

    override open func processEvent( arg0: AWTEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "processEvent", methodSig: "(Ljava/awt/AWTEvent;)V", methodCache: &Window.processEvent_MethodID_9, args: &__args, locals: &__locals )
    }

    override open func processEvent( _ _arg0: AWTEvent? ) {
        processEvent( arg0: _arg0 )
    }

    /// public java.util.Set java.awt.Window.getFocusTraversalKeys(int)

    /// final void java.awt.Window.clearMostRecentFocusOwnerOnHide()

    /// public final void java.awt.Window.setFocusCycleRoot(boolean)

    /// void java.awt.Window.preProcessKeyEvent(java.awt.event.KeyEvent)

    /// void java.awt.Window.postProcessKeyEvent(java.awt.event.KeyEvent)

    /// final void java.awt.Window.mixOnReshaping()

    /// public java.awt.GraphicsConfiguration java.awt.Window.getGraphicsConfiguration()

    /// public java.awt.Component java.awt.Window.getFocusOwner()

    private static var getFocusOwner_MethodID_10: jmethodID?

    open func getFocusOwner() -> Component! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getFocusOwner", methodSig: "()Ljava/awt/Component;", methodCache: &Window.getFocusOwner_MethodID_10, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Component( javaObject: __return ) : nil
    }


    /// void java.awt.Window.adjustListeningChildrenOnParent(long,int)

    /// boolean java.awt.Window.isRecursivelyVisible()

    /// public java.awt.Component java.awt.Window.getMostRecentFocusOwner()

    private static var getMostRecentFocusOwner_MethodID_11: jmethodID?

    open func getMostRecentFocusOwner() -> Component! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getMostRecentFocusOwner", methodSig: "()Ljava/awt/Component;", methodCache: &Window.getMostRecentFocusOwner_MethodID_11, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? Component( javaObject: __return ) : nil
    }


    /// java.awt.Component java.awt.Window.getTemporaryLostComponent()

    /// java.awt.Component java.awt.Window.setTemporaryLostComponent(java.awt.Component)

    /// final java.awt.Container java.awt.Window.getContainer()

    /// final void java.awt.Window.applyCurrentShape()

    /// java.lang.String java.awt.Window.constructComponentName()

    /// void java.awt.Window.resetGC()

    /// public java.awt.Toolkit java.awt.Window.getToolkit()

    /// public void java.awt.Window.show()

    /// public void java.awt.Window.hide()

    /// public void java.awt.Window.setCursor(java.awt.Cursor)

    /// public void java.awt.Window.createBufferStrategy(int)

    private static var createBufferStrategy_MethodID_12: jmethodID?

    open func createBufferStrategy( arg0: Int ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "createBufferStrategy", methodSig: "(I)V", methodCache: &Window.createBufferStrategy_MethodID_12, args: &__args, locals: &__locals )
    }

    open func createBufferStrategy( _ _arg0: Int ) {
        createBufferStrategy( arg0: _arg0 )
    }

    /// public void java.awt.Window.createBufferStrategy(int,java.awt.BufferCapabilities) throws java.awt.AWTException

    private static var createBufferStrategy_MethodID_13: jmethodID?

    open func createBufferStrategy( arg0: Int, arg1: BufferCapabilities? ) throws /* java.awt.AWTException */ {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "createBufferStrategy", methodSig: "(ILjava/awt/BufferCapabilities;)V", methodCache: &Window.createBufferStrategy_MethodID_13, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            throw AWTException( javaObject: throwable )
        }
    }

    open func createBufferStrategy( _ _arg0: Int, _ _arg1: BufferCapabilities? ) throws /* java.awt.AWTException */ {
        try createBufferStrategy( arg0: _arg0, arg1: _arg1 )
    }

    /// public java.awt.image.BufferStrategy java.awt.Window.getBufferStrategy()

    private static var getBufferStrategy_MethodID_14: jmethodID?

    open func getBufferStrategy() -> BufferStrategy! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getBufferStrategy", methodSig: "()Ljava/awt/image/BufferStrategy;", methodCache: &Window.getBufferStrategy_MethodID_14, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? BufferStrategy( javaObject: __return ) : nil
    }


    /// boolean java.awt.Window.dispatchMouseWheelToAncestor(java.awt.event.MouseWheelEvent)

    /// public java.awt.im.InputContext java.awt.Window.getInputContext()

    /// final void java.awt.Window.applyCompoundShape(sun.java2d.pipe.Region)

    /// final java.awt.Point java.awt.Window.getLocationOnWindow()

    /// public final boolean java.awt.Window.isFocusableWindow()

    private static var isFocusableWindow_MethodID_15: jmethodID?

    open func isFocusableWindow() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isFocusableWindow", methodSig: "()Z", methodCache: &Window.isFocusableWindow_MethodID_15, args: &__args, locals: &__locals )
        return JNIType.decode( type: Bool(), from: __return )
    }


    /// private void java.awt.Window.applyShape()

    /// boolean java.awt.Window.isDisposing()

    /// public boolean java.awt.Window.isActive()

    private static var isActive_MethodID_16: jmethodID?

    open func isActive() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isActive", methodSig: "()Z", methodCache: &Window.isActive_MethodID_16, args: &__args, locals: &__locals )
        return JNIType.decode( type: Bool(), from: __return )
    }


    /// static double java.awt.Window.access$1402(java.awt.Window,double)

    /// static float java.awt.Window.access$1502(java.awt.Window,float)

    /// void java.awt.Window.doDispose()

    /// public void java.awt.Window.toBack()

    private static var toBack_MethodID_17: jmethodID?

    open func toBack() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "toBack", methodSig: "()V", methodCache: &Window.toBack_MethodID_17, args: &__args, locals: &__locals )
    }


    /// boolean java.awt.Window.isModalBlocked()

    /// public void java.awt.Window.setLocationByPlatform(boolean)

    private static var setLocationByPlatform_MethodID_18: jmethodID?

    open func setLocationByPlatform( arg0: Bool ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setLocationByPlatform", methodSig: "(Z)V", methodCache: &Window.setLocationByPlatform_MethodID_18, args: &__args, locals: &__locals )
    }

    open func setLocationByPlatform( _ _arg0: Bool ) {
        setLocationByPlatform( arg0: _arg0 )
    }

    /// static void java.awt.Window.updateChildFocusableWindowState(java.awt.Window)

    /// synchronized void java.awt.Window.postWindowEvent(int)

    /// void java.awt.Window.disposeImpl()

    /// final void java.awt.Window.toBack_NoClientCode()

    /// final java.awt.Window java.awt.Window.getOwner_NoClientCode()

    /// java.awt.Dialog java.awt.Window.getModalBlocker()

    /// final java.awt.Window[] java.awt.Window.getOwnedWindows_NoClientCode()

    /// static sun.awt.util.IdentityArrayList java.awt.Window.getAllUnblockedWindows()

    /// void java.awt.Window.updateChildrenBlocking()

    /// java.awt.Window java.awt.Window.getDocumentRoot()

    /// void java.awt.Window.setModalBlocked(java.awt.Dialog,boolean,boolean)

    /// private void java.awt.Window.ownedInit(java.awt.Window)

    /// public java.util.List java.awt.Window.getIconImages()

    private static var getIconImages_MethodID_19: jmethodID?

    open func getIconImages() -> java_util.List! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getIconImages", methodSig: "()Ljava/util/List;", methodCache: &Window.getIconImages_MethodID_19, args: &__args, locals: &__locals )
        defer { JNI.DeleteLocalRef( __return ) }
        return __return != nil ? java_util.ListForward( javaObject: __return ) : nil
    }


    /// public synchronized void java.awt.Window.setIconImages(java.util.List)

    private static var setIconImages_MethodID_20: jmethodID?

    open func setIconImages( arg0: java_util.List? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setIconImages", methodSig: "(Ljava/util/List;)V", methodCache: &Window.setIconImages_MethodID_20, args: &__args, locals: &__locals )
    }

    open func setIconImages( _ _arg0: java_util.List? ) {
        setIconImages( arg0: _arg0 )
    }

    /// public void java.awt.Window.setIconImage(java.awt.Image)

    private static var setIconImage_MethodID_21: jmethodID?

    open func setIconImage( arg0: Image? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setIconImage", methodSig: "(Ljava/awt/Image;)V", methodCache: &Window.setIconImage_MethodID_21, args: &__args, locals: &__locals )
    }

    open func setIconImage( _ _arg0: Image? ) {
        setIconImage( arg0: _arg0 )
    }

    /// public void java.awt.Window.pack()

    private static var pack_MethodID_22: jmethodID?

    open func pack() {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "pack", methodSig: "()V", methodCache: &Window.pack_MethodID_22, args: &__args, locals: &__locals )
    }


    /// void java.awt.Window.setClientSize(int,int)

    /// final void java.awt.Window.toFront_NoClientCode()

    /// public final java.lang.String java.awt.Window.getWarningString()

    private static var getWarningString_MethodID_23: jmethodID?

    open func getWarningString() -> String! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getWarningString", methodSig: "()Ljava/lang/String;", methodCache: &Window.getWarningString_MethodID_23, args: &__args, locals: &__locals )
        return JNIType.decode( type: String(), from: __return )
    }


    /// private void java.awt.Window.setWarningString()

    /// public java.awt.Window[] java.awt.Window.getOwnedWindows()

    private static var getOwnedWindows_MethodID_24: jmethodID?

    open func getOwnedWindows() -> [Window]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getOwnedWindows", methodSig: "()[Ljava/awt/Window;", methodCache: &Window.getOwnedWindows_MethodID_24, args: &__args, locals: &__locals )
        return JNIType.decode( type: [Window](), from: __return )
    }


    /// static sun.awt.util.IdentityArrayList java.awt.Window.getAllWindows()

    /// public static java.awt.Window[] java.awt.Window.getWindows()

    private static var getWindows_MethodID_25: jmethodID?

    open class func getWindows() -> [Window]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/awt/Window", classCache: &WindowJNIClass, methodName: "getWindows", methodSig: "()[Ljava/awt/Window;", methodCache: &getWindows_MethodID_25, args: &__args, locals: &__locals )
        return JNIType.decode( type: [Window](), from: __return )
    }


    /// private static java.awt.Window[] java.awt.Window.getWindows(sun.awt.AppContext)

    /// public static java.awt.Window[] java.awt.Window.getOwnerlessWindows()

    private static var getOwnerlessWindows_MethodID_26: jmethodID?

    open class func getOwnerlessWindows() -> [Window]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallStaticObjectMethod( className: "java/awt/Window", classCache: &WindowJNIClass, methodName: "getOwnerlessWindows", methodSig: "()[Ljava/awt/Window;", methodCache: &getOwnerlessWindows_MethodID_26, args: &__args, locals: &__locals )
        return JNIType.decode( type: [Window](), from: __return )
    }


    /// public synchronized void java.awt.Window.addWindowListener(java.awt.event.WindowListener)

    private static var addWindowListener_MethodID_27: jmethodID?

    open func addWindowListener( arg0: WindowListener? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "addWindowListener", methodSig: "(Ljava/awt/event/WindowListener;)V", methodCache: &Window.addWindowListener_MethodID_27, args: &__args, locals: &__locals )
    }

    open func addWindowListener( _ _arg0: WindowListener? ) {
        addWindowListener( arg0: _arg0 )
    }

    /// public synchronized void java.awt.Window.addWindowStateListener(java.awt.event.WindowStateListener)

    private static var addWindowStateListener_MethodID_28: jmethodID?

    open func addWindowStateListener( arg0: WindowStateListener? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "addWindowStateListener", methodSig: "(Ljava/awt/event/WindowStateListener;)V", methodCache: &Window.addWindowStateListener_MethodID_28, args: &__args, locals: &__locals )
    }

    open func addWindowStateListener( _ _arg0: WindowStateListener? ) {
        addWindowStateListener( arg0: _arg0 )
    }

    /// public synchronized void java.awt.Window.addWindowFocusListener(java.awt.event.WindowFocusListener)

    private static var addWindowFocusListener_MethodID_29: jmethodID?

    open func addWindowFocusListener( arg0: WindowFocusListener? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "addWindowFocusListener", methodSig: "(Ljava/awt/event/WindowFocusListener;)V", methodCache: &Window.addWindowFocusListener_MethodID_29, args: &__args, locals: &__locals )
    }

    open func addWindowFocusListener( _ _arg0: WindowFocusListener? ) {
        addWindowFocusListener( arg0: _arg0 )
    }

    /// public synchronized void java.awt.Window.removeWindowListener(java.awt.event.WindowListener)

    private static var removeWindowListener_MethodID_30: jmethodID?

    open func removeWindowListener( arg0: WindowListener? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "removeWindowListener", methodSig: "(Ljava/awt/event/WindowListener;)V", methodCache: &Window.removeWindowListener_MethodID_30, args: &__args, locals: &__locals )
    }

    open func removeWindowListener( _ _arg0: WindowListener? ) {
        removeWindowListener( arg0: _arg0 )
    }

    /// public synchronized void java.awt.Window.removeWindowStateListener(java.awt.event.WindowStateListener)

    private static var removeWindowStateListener_MethodID_31: jmethodID?

    open func removeWindowStateListener( arg0: WindowStateListener? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "removeWindowStateListener", methodSig: "(Ljava/awt/event/WindowStateListener;)V", methodCache: &Window.removeWindowStateListener_MethodID_31, args: &__args, locals: &__locals )
    }

    open func removeWindowStateListener( _ _arg0: WindowStateListener? ) {
        removeWindowStateListener( arg0: _arg0 )
    }

    /// public synchronized void java.awt.Window.removeWindowFocusListener(java.awt.event.WindowFocusListener)

    private static var removeWindowFocusListener_MethodID_32: jmethodID?

    open func removeWindowFocusListener( arg0: WindowFocusListener? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = jvalue( l: arg0?.localJavaObject( &__locals ) )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "removeWindowFocusListener", methodSig: "(Ljava/awt/event/WindowFocusListener;)V", methodCache: &Window.removeWindowFocusListener_MethodID_32, args: &__args, locals: &__locals )
    }

    open func removeWindowFocusListener( _ _arg0: WindowFocusListener? ) {
        removeWindowFocusListener( arg0: _arg0 )
    }

    /// public synchronized java.awt.event.WindowListener[] java.awt.Window.getWindowListeners()

    private static var getWindowListeners_MethodID_33: jmethodID?

    open func getWindowListeners() -> [WindowListener]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getWindowListeners", methodSig: "()[Ljava/awt/event/WindowListener;", methodCache: &Window.getWindowListeners_MethodID_33, args: &__args, locals: &__locals )
        return JNIType.decode( type: [WindowListenerForward](), from: __return )
    }


    /// public synchronized java.awt.event.WindowFocusListener[] java.awt.Window.getWindowFocusListeners()

    private static var getWindowFocusListeners_MethodID_34: jmethodID?

    open func getWindowFocusListeners() -> [WindowFocusListener]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getWindowFocusListeners", methodSig: "()[Ljava/awt/event/WindowFocusListener;", methodCache: &Window.getWindowFocusListeners_MethodID_34, args: &__args, locals: &__locals )
        return JNIType.decode( type: [WindowFocusListenerForward](), from: __return )
    }


    /// public synchronized java.awt.event.WindowStateListener[] java.awt.Window.getWindowStateListeners()

    private static var getWindowStateListeners_MethodID_35: jmethodID?

    open func getWindowStateListeners() -> [WindowStateListener]! {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallObjectMethod( object: javaObject, methodName: "getWindowStateListeners", methodSig: "()[Ljava/awt/event/WindowStateListener;", methodCache: &Window.getWindowStateListeners_MethodID_35, args: &__args, locals: &__locals )
        return JNIType.decode( type: [WindowStateListenerForward](), from: __return )
    }


    /// protected void java.awt.Window.processWindowEvent(java.awt.event.WindowEvent)

    private static var processWindowEvent_MethodID_36: jmethodID?

    open func processWindowEvent( arg0: WindowEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "processWindowEvent", methodSig: "(Ljava/awt/event/WindowEvent;)V", methodCache: &Window.processWindowEvent_MethodID_36, args: &__args, locals: &__locals )
    }

    open func processWindowEvent( _ _arg0: WindowEvent? ) {
        processWindowEvent( arg0: _arg0 )
    }

    /// protected void java.awt.Window.processWindowFocusEvent(java.awt.event.WindowEvent)

    private static var processWindowFocusEvent_MethodID_37: jmethodID?

    open func processWindowFocusEvent( arg0: WindowEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "processWindowFocusEvent", methodSig: "(Ljava/awt/event/WindowEvent;)V", methodCache: &Window.processWindowFocusEvent_MethodID_37, args: &__args, locals: &__locals )
    }

    open func processWindowFocusEvent( _ _arg0: WindowEvent? ) {
        processWindowFocusEvent( arg0: _arg0 )
    }

    /// protected void java.awt.Window.processWindowStateEvent(java.awt.event.WindowEvent)

    private static var processWindowStateEvent_MethodID_38: jmethodID?

    open func processWindowStateEvent( arg0: WindowEvent? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "processWindowStateEvent", methodSig: "(Ljava/awt/event/WindowEvent;)V", methodCache: &Window.processWindowStateEvent_MethodID_38, args: &__args, locals: &__locals )
    }

    open func processWindowStateEvent( _ _arg0: WindowEvent? ) {
        processWindowStateEvent( arg0: _arg0 )
    }

    /// public final void java.awt.Window.setAlwaysOnTop(boolean) throws java.lang.SecurityException

    private static var setAlwaysOnTop_MethodID_39: jmethodID?

    open func setAlwaysOnTop( arg0: Bool ) throws /* java.lang.SecurityException */ {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setAlwaysOnTop", methodSig: "(Z)V", methodCache: &Window.setAlwaysOnTop_MethodID_39, args: &__args, locals: &__locals )
        if let throwable = JNI.ExceptionCheck() {
            throw java_lang.JavaSecurityException( javaObject: throwable )
        }
    }

    open func setAlwaysOnTop( _ _arg0: Bool ) throws /* java.lang.SecurityException */ {
        try setAlwaysOnTop( arg0: _arg0 )
    }

    /// public final boolean java.awt.Window.isAlwaysOnTop()

    private static var isAlwaysOnTop_MethodID_40: jmethodID?

    open func isAlwaysOnTop() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isAlwaysOnTop", methodSig: "()Z", methodCache: &Window.isAlwaysOnTop_MethodID_40, args: &__args, locals: &__locals )
        return JNIType.decode( type: Bool(), from: __return )
    }


    /// public boolean java.awt.Window.isFocused()

    private static var isFocused_MethodID_41: jmethodID?

    open func isFocused() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isFocused", methodSig: "()Z", methodCache: &Window.isFocused_MethodID_41, args: &__args, locals: &__locals )
        return JNIType.decode( type: Bool(), from: __return )
    }


    /// public boolean java.awt.Window.getFocusableWindowState()

    private static var getFocusableWindowState_MethodID_42: jmethodID?

    open func getFocusableWindowState() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "getFocusableWindowState", methodSig: "()Z", methodCache: &Window.getFocusableWindowState_MethodID_42, args: &__args, locals: &__locals )
        return JNIType.decode( type: Bool(), from: __return )
    }


    /// public void java.awt.Window.setFocusableWindowState(boolean)

    private static var setFocusableWindowState_MethodID_43: jmethodID?

    open func setFocusableWindowState( arg0: Bool ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setFocusableWindowState", methodSig: "(Z)V", methodCache: &Window.setFocusableWindowState_MethodID_43, args: &__args, locals: &__locals )
    }

    open func setFocusableWindowState( _ _arg0: Bool ) {
        setFocusableWindowState( arg0: _arg0 )
    }

    /// public void java.awt.Window.applyResourceBundle(java.util.ResourceBundle)

    private static var applyResourceBundle_MethodID_44: jmethodID?

    open func applyResourceBundle( arg0: java_util.ResourceBundle? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "applyResourceBundle", methodSig: "(Ljava/util/ResourceBundle;)V", methodCache: &Window.applyResourceBundle_MethodID_44, args: &__args, locals: &__locals )
    }

    open func applyResourceBundle( _ _arg0: java_util.ResourceBundle? ) {
        applyResourceBundle( arg0: _arg0 )
    }

    /// public void java.awt.Window.applyResourceBundle(java.lang.String)

    private static var applyResourceBundle_MethodID_45: jmethodID?

    open func applyResourceBundle( arg0: String? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "applyResourceBundle", methodSig: "(Ljava/lang/String;)V", methodCache: &Window.applyResourceBundle_MethodID_45, args: &__args, locals: &__locals )
    }

    open func applyResourceBundle( _ _arg0: String? ) {
        applyResourceBundle( arg0: _arg0 )
    }

    /// void java.awt.Window.addOwnedWindow(java.lang.ref.WeakReference)

    /// void java.awt.Window.removeOwnedWindow(java.lang.ref.WeakReference)

    /// void java.awt.Window.connectOwnedWindow(java.awt.Window)

    /// private void java.awt.Window.addToWindowList()

    /// private static void java.awt.Window.removeFromWindowList(sun.awt.AppContext,java.lang.ref.WeakReference)

    /// private void java.awt.Window.removeFromWindowList()

    /// private void java.awt.Window.initDeserializedWindow()

    /// private void java.awt.Window.deserializeResources(java.io.ObjectInputStream) throws java.lang.ClassNotFoundException,java.io.IOException,java.awt.HeadlessException

    /// public void java.awt.Window.setLocationRelativeTo(java.awt.Component)

    private static var setLocationRelativeTo_MethodID_46: jmethodID?

    open func setLocationRelativeTo( arg0: Component? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        JNIMethod.CallVoidMethod( object: javaObject, methodName: "setLocationRelativeTo", methodSig: "(Ljava/awt/Component;)V", methodCache: &Window.setLocationRelativeTo_MethodID_46, args: &__args, locals: &__locals )
    }

    open func setLocationRelativeTo( _ _arg0: Component? ) {
        setLocationRelativeTo( arg0: _arg0 )
    }

    /// void java.awt.Window.deliverMouseWheelToAncestor(java.awt.event.MouseWheelEvent)

    /// public boolean java.awt.Window.isLocationByPlatform()

    private static var isLocationByPlatform_MethodID_47: jmethodID?

    open func isLocationByPlatform() -> Bool {
        var __args = [jvalue]( repeating: jvalue(), count: 1 )
        var __locals = [jobject]()
        let __return = JNIMethod.CallBooleanMethod( object: javaObject, methodName: "isLocationByPlatform", methodSig: "()Z", methodCache: &Window.isLocationByPlatform_MethodID_47, args: &__args, locals: &__locals )
        return JNIType.decode( type: Bool(), from: __return )
    }


    /// private static void java.awt.Window.setLayersOpaque(java.awt.Component,boolean)

    /// private void java.awt.Window.applyOpacity()

    /// private void java.awt.Window.applyOpaque()

    /// private void java.awt.Window.updateWindow()

    /// private java.awt.geom.Point2D java.awt.Window.calculateSecurityWarningPosition(double,double,double,double)

    /// static boolean java.awt.Window.access$802(java.awt.Window,boolean)

    /// static int java.awt.Window.access$1202(java.awt.Window,int)

    /// In declared protocol but not defined.. ///

    /// public abstract javax.accessibility.AccessibleContext javax.accessibility.Accessible.getAccessibleContext()

}
private typealias Window_paint_0_type = @convention(c) ( _: UnsafeMutablePointer<JNIEnv?>, _: jobject?, _: jobject? ) -> ()

private func Window_paint_0( _ __env: UnsafeMutablePointer<JNIEnv?>, _ __this: jobject?, _ arg0: jobject? ) -> () {
    WindowBase.swiftObject( jniEnv: __env, javaObject: __this ).paint( arg0 != nil ? Graphics( javaObject: arg0 ) : nil )
}

open class WindowBase: Window {

    private static var WindowBaseJNIClass: jclass?
    private static var nativesRegistered = false

    private static func registerNatives() {
        if ( !nativesRegistered ) {
            var natives = [JNINativeMethod]()

            let Window_paint_0_thunk: Window_paint_0_type = Window_paint_0
            natives.append( JNINativeMethod( name: strdup("__paint"), signature: strdup("(Ljava/awt/Graphics;)V"), fnPtr: unsafeBitCast( Window_paint_0_thunk, to: UnsafeMutableRawPointer.self ) ) )

            withUnsafePointer(to: &natives[0]) {
                nativesPtr in
                let clazz = JNI.FindClass( "org/genie/java_awt/WindowProxy" )
                if JNI.api.RegisterNatives( JNI.env, clazz, nativesPtr, jint(natives.count) ) != jint(JNI_OK) {
                    JNI.report( "Unable to register java natives" )
                }
            }

            nativesRegistered = true
        }
    }

    override open var javaObject: jobject? {
        get {
            return super.javaObject
        }
        set(newValue) {
            super.javaObject = newValue
            WindowBase.registerNatives()
            updateSwiftObject()
        }
    }

    public required init( javaObject: jobject? ) {
        super.init( javaObject: javaObject )
    }

    static func swiftObject( jniEnv: UnsafeMutablePointer<JNIEnv?>?, javaObject: jobject? ) -> WindowBase {
        return unsafeBitCast( swiftPointer( jniEnv: jniEnv, object: javaObject ), to: WindowBase.self )
    }

    /// public java.awt.Window(java.awt.Window,java.awt.GraphicsConfiguration)

    private static var new_MethodID_48: jmethodID?

    public convenience init( arg0: Window?, arg1: GraphicsConfiguration? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 3 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )
        __args[1] = JNIType.encode( value: arg1, locals: &__locals )

        self.init( javaObject: nil )
        __args[2] = swiftValue()

        let __object = JNIMethod.NewObject( className: "org/genie/java_awt/WindowProxy", classCache: &WindowBase.WindowBaseJNIClass, methodSig: "(Ljava/awt/Window;Ljava/awt/GraphicsConfiguration;J)V", methodCache: &WindowBase.new_MethodID_48, args: &__args, locals: &__locals )
        self.javaObject = __object
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Window?, _ _arg1: GraphicsConfiguration? ) {
        self.init( arg0: _arg0, arg1: _arg1 )
    }

    /// java.awt.Window(java.awt.GraphicsConfiguration)

    /// java.awt.Window() throws java.awt.HeadlessException

    /// public java.awt.Window(java.awt.Frame)

    /// public java.awt.Window(java.awt.Window)

    private static var new_MethodID_49: jmethodID?

    public convenience init( arg0: Window? ) {
        var __args = [jvalue]( repeating: jvalue(), count: 2 )
        var __locals = [jobject]()
        __args[0] = JNIType.encode( value: arg0, locals: &__locals )

        self.init( javaObject: nil )
        __args[1] = swiftValue()

        let __object = JNIMethod.NewObject( className: "org/genie/java_awt/WindowProxy", classCache: &WindowBase.WindowBaseJNIClass, methodSig: "(Ljava/awt/Window;J)V", methodCache: &WindowBase.new_MethodID_49, args: &__args, locals: &__locals )
        self.javaObject = __object
        JNI.DeleteLocalRef( __object )
    }

    public convenience init( _ _arg0: Window? ) {
        self.init( arg0: _arg0 )
    }

}
